package uaparser

const (
	UserAgent           = "user-agent"
	Model               = "model"
	Mobile              = "mobile"
	Platform            = "platform"
	Bitness             = "bitness"
	CHHeader            = "sec-ch-ua"
	CHHeaderFullVerList = CHHeader + "-full-version-list"
	CHHeaderArch        = CHHeader + "-arch"
	CHHeaderBitness     = CHHeader + "-" + Bitness
	CHHeaderFormFactors = CHHeader + "-form-factors"
	CHHeaderMobile      = CHHeader + "-" + Mobile
	CHHeaderModel       = CHHeader + "-" + Model
	CHHeaderPlatform    = CHHeader + "-" + Platform
	CHHeaderPlatformVer = CHHeaderPlatform + "-version"
)

// for regex-base impl
const (
	Name         = "name"
	Version      = "version"
	Type         = "type"
	Architecture = "architecture"
	Vendor       = "vendor"
	Console      = "console"
	Major        = "major"
	SmartTV      = "smarttv"
	Wearable     = "wearable"
	XR           = "xr"
	Embedded     = "embedded"
	UABrowser    = "browser"
	UACpu        = "cpu"
	UADevice     = "device"
	UAEngine     = "engine"
	UAOS         = "os"
	UAResult     = "result"
	Tablet       = "tablet"
	Crawler      = "crawler"
	CLI          = "cli"
	Email        = "email"
	Fetcher      = "fetcher"
	InApp        = "inapp"
	MediaPlayer  = "mediaplayer"
	Library      = "library"

	Windows    = "Windows"
	Opera      = "Opera"
	Edge       = "Edge"
	Baidu      = "Baidu"
	Chromium   = "Chromium"
	Amazon     = "Amazon"
	Apple      = "Apple"
	ASUS       = "ASUS"
	Blackberry = "BlackBerry"
	Google     = "Google"
	Huawei     = "Huawei"
	Lenovo     = "Lenovo"
	Honor      = "Honor"
	LG         = "LG"
	Microsoft  = "Microsoft"
	Motorola   = "Motorola"
	OPPO       = "OPPO"
	Samsung    = "Samsung"
	Sharp      = "Sharp"
	Sony       = "Sony"
	Xiaomi     = "Xiaomi"
	Zebra      = "Zebra"
	Chromecast = "Chromecast"
	Xbox       = "Xbox"
	Facebook   = "Facebook"
)
